# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e59c2c4f9488b134767c98e3f45ed86e41ede9a534df5e68302ee856b985aa44e0d3abc2ff05c7f57863b19a5925e43ce22bb406f71487c0390828e04295ce76

test:
  secret_key_base: c0cb15eba90c3668dd89c0a08ee84f11c46e54a0038e9fc004e7768db59cf52598cacc31bffa227eb14f912a0d6ab21993b3321be6bde8b9d54669e0597d43d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
